=pod

=head1 NAME

virt-pack - convert virtual machines from an image descriptor into VMware(tm) format

=head1 SYNOPSIS

B<virt-pack> [OPTION]... IMAGE.XML

=head1 DESCRIPTION

B<virt-pack> is a command line tool for converting virtual machines from an
XML image descriptor C<IMAGE.XML> (L<virt-image(5)>) to a VMware(tm) format machine. 
The basic configuration of the virtual machine are taken from the XML descriptor (e.g., 
disk image files, memory, name, vcpus) and a new VMware(tm) configuration file is created using
these values. The conversion process requires that all necessary kernel modules and configuration 
to boot using VMware are completed prior to running this tool. 


=head1 OPTIONS

Any of the options can be omitted, in which case B<virt-pack> will use defaults when required.

=over 4

=item -h, --help

Show the help message and exit

=item  -o OUTPUT , --output=NAME  

Directory in which packaged tar file will be placed

=item -d, --debug

Print debugging information

=back

=head1 EXAMPLES

Convert a guest from C<image.xml>:

  # virt-pack image.xml

Convert a guest and output the created file to /tmp

  # virt-pack image.xml -o /tmp

=head1 AUTHOR

Written by David Lutterkort and Joey Boggs

See the AUTHORS file in the source distribution for the complete list of credits.

=head1 BUGS

Report bugs to the mailing list C<http://www.redhat.com/mailman/listinfo/et-mgmt-tools>
or directly to BugZilla C<http://bugzilla.redhat.com/bugzilla/> against the
C<Fedora> product, and the C<python-virtinst> component.

=head1 COPYRIGHT

Copyright (C) 2006-2008 Red Hat, Inc, and various contributors. 
This is free software. You may redistribute copies of it under the terms of the GNU General 
Public License C<http://www.gnu.org/licenses/gpl.html>. There is NO WARRANTY, to the extent 
permitted by law.

=head1 SEE ALSO

L<virt-pack(1)>, L<virt-image(5)>, the project website
C<http://virt-manager.org>

=cut

