=pod

=head1 NAME

virt-image - create virtual machines from an image descriptor

=head1 SYNOPSIS

B<virt-image> [OPTION]... IMAGE.XML

=head1 DESCRIPTION

B<virt-image> is a command line tool for creating virtual machines from an
XML image descriptor C<IMAGE.XML> (L<virt-image(5)>). Most attributes of
the virtual machine are taken from the XML descriptor (e.g., where the
files to back the virtual machine's disks are and how to map them into the
guest), though certain information must be added on the command line, such
as the name of the guest. Missing information will be queried
interactively.

The XML descriptor defines most attributes of the guest, making it possible
to bundle and distribute it together with the files backing the guest's
disks.

=head1 OPTIONS

Any of the options can be omitted, in which case B<virt-image> will either
use defaults from the XML descriptor or interactively prompt for input as
required. When defaults are taken from the XML descriptor, they are
indicated below as a path.

=over 4

=item -h, --help

Show the help message and exit

=item  -n NAME, --name=NAME  

Name of the guest instance

=item -r MEMORY, --ram=MEMORY

Memory to allocate for guest instance in megabytes. Defaults to
C</image/devices/memory> in the XML descriptor.

=item  -u UUID, --uuid=UUID  

UUID for the guest; if none is given a random UUID will be generated. If
you specify UUID, you should use a 32-digit hexadecimal number.

=item --vcpus=VCPUS 

Number of vcpus to configure for your guest. Defaults to
C</image/devices/vcpu> in the XML descriptor.

=item  --check-cpu

Check that vcpus do not exceed physical CPUs and warn if they do.

=item -m MAC, --mac=MAC

Fixed MAC address for the guest. See L<virt-install(1)> for details

=item -b BRIDGE, --bridge=BRIDGE

Bridge device to connect the guest NIC to. See L<virt-install(1)> for details

=item -w NETWORK, --network=NETWORK

Connect the guest to the host network. See L<virt-install(1)> for details

=item --vnc

Setup a virtual console in the guest and export it as a VNC server in
the host. See L<virt-install(1)> for details

=item --vncport=VNCPORT

Request a permanent, statically assigned port number for the guest VNC
console. See L<virt-install(1)> for details

=item --sdl

Setup a virtual console in the guest and display an SDL window in the
host to render the output. See L<virt-install(1)> for details

=item --nographics

Disable all interactive prompts for the guest virtual console. See
L<virt-install(1)> for details

=item -k KEYMAP, --keymap=KEYMAP

Request that the virtual console be configured to run with a non-English
keyboard layout.

=item --connect=CONNECT     Connect to hypervisor with URI

Connect to a non-default hypervisor. See L<virt-install(1)> for details

=item --noapic

Disables APIC for fully virtualized guest (overrides value in XML descriptor)

=item --noacpi

Disables ACPI for fully virtualized guest (overrides value in XML descriptor)

=item -d, --debug

Print debugging information

=item -p, --print

Print the libvirt XML, but do not start the guest.

=item --boot=BOOT

The zero-based index of the boot record to use. The XML descriptor can
contain multiple C</image/domain/boot> elements for use on different
hypervisors. By default, the one that is most appropriate for the current
hypervisor is selected.

=item --force

Prevent interactive prompts. If the intended prompt was a yes/no prompt, always
say yes. For any other prompts, the application will exit.

=head1 EXAMPLES

Create and start a guest called C<example> with a VNC console from
C<image.xml>:

  # virt-image --name example --vnc -i image.xml

Print the libvirt XML for a guest called C<example> without graphics, but
do not create or start a virtual machine:

  # virt-image --print --name example --nographics --image image.xml

=head1 AUTHOR

Written by David Lutterkort. See the AUTHORS file in the source distribution for
the complete list of credits.

=head1 BUGS

Report bugs to the mailing list C<http://www.redhat.com/mailman/listinfo/et-mgmt-tools>
or directly to BugZilla C<http://bugzilla.redhat.com/bugzilla/> against the
C<Fedora> product, and the C<python-virtinst> component.

=head1 COPYRIGHT

Copyright (C) 2006-2007 Red Hat, Inc, and various contributors. 
This is free software. You may redistribute copies of it under the terms of the GNU General 
Public License C<http://www.gnu.org/licenses/gpl.html>. There is NO WARRANTY, to the extent 
permitted by law.

=head1 SEE ALSO

L<virt-image(5)>, L<virt-install(1)>, the project website
C<http://virt-manager.org>

=cut

