#!/usr/bin/env ruby

ip_address = nil

while ( ip_address.nil? )
  ifconfig = `ifconfig eth0`
  ifconfig.each_line do |l|
    if ( l =~ /inet addr:([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\s/ )
      ip_address = $1
    end
  end
end

open( "/etc/vm2-support.conf", 'w' ) do |conf|
  conf.puts( "IP_ADDRESS=#{ip_address}" )
end
